@startuml
set separator none
title Infrastructure

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("EventTicketSystemApplication.EventTicketSystemApplication_boundary", "EventTicketSystemApplication", $tags="") {
  Component(EventTicketSystemApplication.EventTicketSystemApplication.Organization, "Organization", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "Sales & Ticketing", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "Shared Kernel", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, "UI (Vaadin driving adapter)", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.Core, "Core", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, "Infrastructure", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "Catalog & Events", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, "Platform Governance", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "Identity & Access", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, "Messaging & Support", $techn="Module", $descr="", $tags="", $link="")
  Component(EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "Notifications", $techn="Module", $descr="", $tags="", $link="")
}

Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.Organization, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.Core, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, EventTicketSystemApplication.EventTicketSystemApplication.Core, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Organization, EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Core, EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Core, EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Core, EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Core, EventTicketSystemApplication.EventTicketSystemApplication.Organization, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Core, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Core, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, EventTicketSystemApplication.EventTicketSystemApplication.Organization, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, EventTicketSystemApplication.EventTicketSystemApplication.Core, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Notifications, EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Notifications, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Notifications, EventTicketSystemApplication.EventTicketSystemApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.Core, "listens to", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.Organization, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, EventTicketSystemApplication.EventTicketSystemApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, EventTicketSystemApplication.EventTicketSystemApplication.Organization, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, EventTicketSystemApplication.EventTicketSystemApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, EventTicketSystemApplication.EventTicketSystemApplication.Organization, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.UIVaadindrivingadapter, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.PlatformGovernance, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.CatalogEvents, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.Organization, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.MessagingSupport, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.Notifications, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.IdentityAccess, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, EventTicketSystemApplication.EventTicketSystemApplication.Core, "uses", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(EventTicketSystemApplication.EventTicketSystemApplication.SalesTicketing, EventTicketSystemApplication.EventTicketSystemApplication.Infrastructure, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml